spring.application.name=flight-archive-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/flight_archive_db
spring.datasource.username=alikaracor
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/db.changelog-master.yaml

app.kafka.flight-events-topic=flight.events

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=flight-archive-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

app.kafka.flight-events-dlt-topic=flight.events.DLT

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.alikaracor.learning.flight_archive_service.event
spring.kafka.consumer.properties.spring.json.value.default.type=com.alikaracor.learning.flight_archive_service.event.FlightEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when-authorized

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/public-key.pem





